// Code generated by protoc-gen-go. DO NOT EDIT.
// source: attachment.proto

package go_micro_srv_attachment_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AttachType int32

const (
	AttachType_IMAGE AttachType = 0
	AttachType_VIDEO AttachType = 1
)

var AttachType_name = map[int32]string{
	0: "IMAGE",
	1: "VIDEO",
}

var AttachType_value = map[string]int32{
	"IMAGE": 0,
	"VIDEO": 1,
}

func (x AttachType) String() string {
	return proto.EnumName(AttachType_name, int32(x))
}

func (AttachType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_50ce80bdd3ef17d6, []int{0}
}

type Attachment struct {
	Id                   int32      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url                  string     `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	UserId               int32      `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AttachType           AttachType `protobuf:"varint,4,opt,name=attach_type,json=attachType,proto3,enum=go.micro.srv.attachment.v1.AttachType" json:"attach_type,omitempty"`
	CreatedAt            int32      `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ImageExt             *ImageExt  `protobuf:"bytes,6,opt,name=image_ext,json=imageExt,proto3" json:"image_ext,omitempty"`
	VideoExt             *VideoExt  `protobuf:"bytes,7,opt,name=video_ext,json=videoExt,proto3" json:"video_ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Attachment) Reset()         { *m = Attachment{} }
func (m *Attachment) String() string { return proto.CompactTextString(m) }
func (*Attachment) ProtoMessage()    {}
func (*Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_50ce80bdd3ef17d6, []int{0}
}

func (m *Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attachment.Unmarshal(m, b)
}
func (m *Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attachment.Marshal(b, m, deterministic)
}
func (m *Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attachment.Merge(m, src)
}
func (m *Attachment) XXX_Size() int {
	return xxx_messageInfo_Attachment.Size(m)
}
func (m *Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_Attachment proto.InternalMessageInfo

func (m *Attachment) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Attachment) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Attachment) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Attachment) GetAttachType() AttachType {
	if m != nil {
		return m.AttachType
	}
	return AttachType_IMAGE
}

func (m *Attachment) GetCreatedAt() int32 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Attachment) GetImageExt() *ImageExt {
	if m != nil {
		return m.ImageExt
	}
	return nil
}

func (m *Attachment) GetVideoExt() *VideoExt {
	if m != nil {
		return m.VideoExt
	}
	return nil
}

type ImageExt struct {
	W                    int32    `protobuf:"varint,1,opt,name=w,proto3" json:"w,omitempty"`
	H                    int32    `protobuf:"varint,2,opt,name=h,proto3" json:"h,omitempty"`
	Mime                 string   `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageExt) Reset()         { *m = ImageExt{} }
func (m *ImageExt) String() string { return proto.CompactTextString(m) }
func (*ImageExt) ProtoMessage()    {}
func (*ImageExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_50ce80bdd3ef17d6, []int{1}
}

func (m *ImageExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageExt.Unmarshal(m, b)
}
func (m *ImageExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageExt.Marshal(b, m, deterministic)
}
func (m *ImageExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageExt.Merge(m, src)
}
func (m *ImageExt) XXX_Size() int {
	return xxx_messageInfo_ImageExt.Size(m)
}
func (m *ImageExt) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageExt.DiscardUnknown(m)
}

var xxx_messageInfo_ImageExt proto.InternalMessageInfo

func (m *ImageExt) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *ImageExt) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *ImageExt) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

type VideoExt struct {
	W                    int32    `protobuf:"varint,1,opt,name=w,proto3" json:"w,omitempty"`
	H                    int32    `protobuf:"varint,2,opt,name=h,proto3" json:"h,omitempty"`
	Mime                 string   `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VideoExt) Reset()         { *m = VideoExt{} }
func (m *VideoExt) String() string { return proto.CompactTextString(m) }
func (*VideoExt) ProtoMessage()    {}
func (*VideoExt) Descriptor() ([]byte, []int) {
	return fileDescriptor_50ce80bdd3ef17d6, []int{2}
}

func (m *VideoExt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VideoExt.Unmarshal(m, b)
}
func (m *VideoExt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VideoExt.Marshal(b, m, deterministic)
}
func (m *VideoExt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VideoExt.Merge(m, src)
}
func (m *VideoExt) XXX_Size() int {
	return xxx_messageInfo_VideoExt.Size(m)
}
func (m *VideoExt) XXX_DiscardUnknown() {
	xxx_messageInfo_VideoExt.DiscardUnknown(m)
}

var xxx_messageInfo_VideoExt proto.InternalMessageInfo

func (m *VideoExt) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *VideoExt) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *VideoExt) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

func (m *VideoExt) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

type AttachmentDetailByIdsReq struct {
	Ids                  []int32  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachmentDetailByIdsReq) Reset()         { *m = AttachmentDetailByIdsReq{} }
func (m *AttachmentDetailByIdsReq) String() string { return proto.CompactTextString(m) }
func (*AttachmentDetailByIdsReq) ProtoMessage()    {}
func (*AttachmentDetailByIdsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_50ce80bdd3ef17d6, []int{3}
}

func (m *AttachmentDetailByIdsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachmentDetailByIdsReq.Unmarshal(m, b)
}
func (m *AttachmentDetailByIdsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachmentDetailByIdsReq.Marshal(b, m, deterministic)
}
func (m *AttachmentDetailByIdsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachmentDetailByIdsReq.Merge(m, src)
}
func (m *AttachmentDetailByIdsReq) XXX_Size() int {
	return xxx_messageInfo_AttachmentDetailByIdsReq.Size(m)
}
func (m *AttachmentDetailByIdsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachmentDetailByIdsReq.DiscardUnknown(m)
}

var xxx_messageInfo_AttachmentDetailByIdsReq proto.InternalMessageInfo

func (m *AttachmentDetailByIdsReq) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type AddAttachmentReq struct {
	Url                  string     `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	UserId               int32      `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AttachType           AttachType `protobuf:"varint,3,opt,name=attach_type,json=attachType,proto3,enum=go.micro.srv.attachment.v1.AttachType" json:"attach_type,omitempty"`
	ImageExt             *ImageExt  `protobuf:"bytes,5,opt,name=image_ext,json=imageExt,proto3" json:"image_ext,omitempty"`
	VideoExt             *VideoExt  `protobuf:"bytes,6,opt,name=video_ext,json=videoExt,proto3" json:"video_ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AddAttachmentReq) Reset()         { *m = AddAttachmentReq{} }
func (m *AddAttachmentReq) String() string { return proto.CompactTextString(m) }
func (*AddAttachmentReq) ProtoMessage()    {}
func (*AddAttachmentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_50ce80bdd3ef17d6, []int{4}
}

func (m *AddAttachmentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAttachmentReq.Unmarshal(m, b)
}
func (m *AddAttachmentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAttachmentReq.Marshal(b, m, deterministic)
}
func (m *AddAttachmentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAttachmentReq.Merge(m, src)
}
func (m *AddAttachmentReq) XXX_Size() int {
	return xxx_messageInfo_AddAttachmentReq.Size(m)
}
func (m *AddAttachmentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAttachmentReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddAttachmentReq proto.InternalMessageInfo

func (m *AddAttachmentReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *AddAttachmentReq) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddAttachmentReq) GetAttachType() AttachType {
	if m != nil {
		return m.AttachType
	}
	return AttachType_IMAGE
}

func (m *AddAttachmentReq) GetImageExt() *ImageExt {
	if m != nil {
		return m.ImageExt
	}
	return nil
}

func (m *AddAttachmentReq) GetVideoExt() *VideoExt {
	if m != nil {
		return m.VideoExt
	}
	return nil
}

type AttachmentDetailByIdsRep struct {
	Attachment           map[int32]*Attachment `protobuf:"bytes,1,rep,name=attachment,proto3" json:"attachment,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AttachmentDetailByIdsRep) Reset()         { *m = AttachmentDetailByIdsRep{} }
func (m *AttachmentDetailByIdsRep) String() string { return proto.CompactTextString(m) }
func (*AttachmentDetailByIdsRep) ProtoMessage()    {}
func (*AttachmentDetailByIdsRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_50ce80bdd3ef17d6, []int{5}
}

func (m *AttachmentDetailByIdsRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachmentDetailByIdsRep.Unmarshal(m, b)
}
func (m *AttachmentDetailByIdsRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachmentDetailByIdsRep.Marshal(b, m, deterministic)
}
func (m *AttachmentDetailByIdsRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachmentDetailByIdsRep.Merge(m, src)
}
func (m *AttachmentDetailByIdsRep) XXX_Size() int {
	return xxx_messageInfo_AttachmentDetailByIdsRep.Size(m)
}
func (m *AttachmentDetailByIdsRep) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachmentDetailByIdsRep.DiscardUnknown(m)
}

var xxx_messageInfo_AttachmentDetailByIdsRep proto.InternalMessageInfo

func (m *AttachmentDetailByIdsRep) GetAttachment() map[int32]*Attachment {
	if m != nil {
		return m.Attachment
	}
	return nil
}

type AddAttachmentReqRep struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAttachmentReqRep) Reset()         { *m = AddAttachmentReqRep{} }
func (m *AddAttachmentReqRep) String() string { return proto.CompactTextString(m) }
func (*AddAttachmentReqRep) ProtoMessage()    {}
func (*AddAttachmentReqRep) Descriptor() ([]byte, []int) {
	return fileDescriptor_50ce80bdd3ef17d6, []int{6}
}

func (m *AddAttachmentReqRep) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAttachmentReqRep.Unmarshal(m, b)
}
func (m *AddAttachmentReqRep) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAttachmentReqRep.Marshal(b, m, deterministic)
}
func (m *AddAttachmentReqRep) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAttachmentReqRep.Merge(m, src)
}
func (m *AddAttachmentReqRep) XXX_Size() int {
	return xxx_messageInfo_AddAttachmentReqRep.Size(m)
}
func (m *AddAttachmentReqRep) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAttachmentReqRep.DiscardUnknown(m)
}

var xxx_messageInfo_AddAttachmentReqRep proto.InternalMessageInfo

func (m *AddAttachmentReqRep) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("go.micro.srv.attachment.v1.AttachType", AttachType_name, AttachType_value)
	proto.RegisterType((*Attachment)(nil), "go.micro.srv.attachment.v1.Attachment")
	proto.RegisterType((*ImageExt)(nil), "go.micro.srv.attachment.v1.ImageExt")
	proto.RegisterType((*VideoExt)(nil), "go.micro.srv.attachment.v1.VideoExt")
	proto.RegisterType((*AttachmentDetailByIdsReq)(nil), "go.micro.srv.attachment.v1.AttachmentDetailByIdsReq")
	proto.RegisterType((*AddAttachmentReq)(nil), "go.micro.srv.attachment.v1.AddAttachmentReq")
	proto.RegisterType((*AttachmentDetailByIdsRep)(nil), "go.micro.srv.attachment.v1.AttachmentDetailByIdsRep")
	proto.RegisterMapType((map[int32]*Attachment)(nil), "go.micro.srv.attachment.v1.AttachmentDetailByIdsRep.AttachmentEntry")
	proto.RegisterType((*AddAttachmentReqRep)(nil), "go.micro.srv.attachment.v1.AddAttachmentReqRep")
}

func init() { proto.RegisterFile("attachment.proto", fileDescriptor_50ce80bdd3ef17d6) }

var fileDescriptor_50ce80bdd3ef17d6 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xd1, 0x8a, 0x13, 0x31,
	0x14, 0x86, 0xcd, 0x74, 0xd3, 0xed, 0x9c, 0xca, 0x3a, 0x44, 0xc1, 0xb0, 0x20, 0x0c, 0x83, 0xca,
	0x20, 0x32, 0x60, 0xbd, 0x91, 0xc5, 0x9b, 0x91, 0x96, 0x65, 0x2e, 0x44, 0x09, 0xb2, 0xb7, 0x25,
	0x36, 0x87, 0x6d, 0xb0, 0xb3, 0x53, 0xd3, 0x74, 0x76, 0xe7, 0x1d, 0x7c, 0x1d, 0x9f, 0xc9, 0xd7,
	0x90, 0xa4, 0xd3, 0x6d, 0xad, 0xee, 0xae, 0xd6, 0xbb, 0x3f, 0xc9, 0x39, 0xff, 0x21, 0xff, 0x37,
	0x13, 0x88, 0xa4, 0xb5, 0x72, 0x32, 0x2d, 0xf1, 0xc2, 0x66, 0x73, 0x53, 0xd9, 0x8a, 0x1d, 0x9f,
	0x57, 0x59, 0xa9, 0x27, 0xa6, 0xca, 0x16, 0xa6, 0xce, 0xb6, 0x8e, 0xeb, 0x57, 0xc9, 0xf7, 0x00,
	0x20, 0xbf, 0xde, 0x61, 0x47, 0x10, 0x68, 0xc5, 0x49, 0x4c, 0x52, 0x2a, 0x02, 0xad, 0x58, 0x04,
	0x9d, 0xa5, 0x99, 0xf1, 0x20, 0x26, 0x69, 0x28, 0x9c, 0x64, 0x8f, 0xe1, 0x70, 0xb9, 0x40, 0x33,
	0xd6, 0x8a, 0x77, 0x7c, 0x59, 0xd7, 0x2d, 0x0b, 0xc5, 0x4e, 0xa1, 0xbf, 0xb2, 0x1e, 0xdb, 0x66,
	0x8e, 0xfc, 0x20, 0x26, 0xe9, 0xd1, 0xe0, 0x79, 0x76, 0xf3, 0xec, 0x6c, 0x35, 0xf7, 0x53, 0x33,
	0x47, 0x01, 0xf2, 0x5a, 0xb3, 0x27, 0x00, 0x13, 0x83, 0xd2, 0xa2, 0x1a, 0x4b, 0xcb, 0xa9, 0x1f,
	0x12, 0xb6, 0x3b, 0xb9, 0x65, 0x39, 0x84, 0xba, 0x94, 0xe7, 0x38, 0xc6, 0x2b, 0xcb, 0xbb, 0x31,
	0x49, 0xfb, 0x83, 0xa7, 0xb7, 0x4d, 0x29, 0x5c, 0xf1, 0xe8, 0xca, 0x8a, 0x9e, 0x6e, 0x95, 0xb3,
	0xa8, 0xb5, 0xc2, 0xca, 0x5b, 0x1c, 0xde, 0x6d, 0x71, 0xe6, 0x8a, 0xbd, 0x45, 0xdd, 0xaa, 0xe4,
	0x04, 0x7a, 0x6b, 0x63, 0x76, 0x1f, 0xc8, 0x65, 0x9b, 0x19, 0xb9, 0x74, 0xab, 0xa9, 0x0f, 0x8c,
	0x0a, 0x32, 0x65, 0x0c, 0x0e, 0x4a, 0x5d, 0xa2, 0xcf, 0x2a, 0x14, 0x5e, 0x27, 0x1f, 0xa1, 0xb7,
	0x76, 0xfc, 0xd7, 0x5e, 0xf6, 0x08, 0xe8, 0xa4, 0xaa, 0xd1, 0xf8, 0x7c, 0x43, 0xb1, 0x5a, 0x24,
	0x2f, 0x81, 0x6f, 0x20, 0x0e, 0xd1, 0x4a, 0x3d, 0x7b, 0xd7, 0x14, 0x6a, 0x21, 0xf0, 0xab, 0x43,
	0xa8, 0xd5, 0x82, 0x93, 0xb8, 0x93, 0x52, 0xe1, 0x64, 0xf2, 0x2d, 0x80, 0x28, 0x57, 0x6a, 0xd3,
	0xd1, 0x96, 0x39, 0xd2, 0xe4, 0x8f, 0xa4, 0x83, 0xdb, 0x48, 0x77, 0xf6, 0x26, 0xfd, 0x0b, 0x4a,
	0xfa, 0xff, 0x28, 0xbb, 0x7b, 0xa1, 0xfc, 0x41, 0x6e, 0x4c, 0x6f, 0xce, 0x14, 0xc0, 0xc6, 0xc0,
	0x87, 0xd8, 0x1f, 0x0c, 0xef, 0xbe, 0xea, 0xef, 0x4e, 0x5b, 0x07, 0xa3, 0x0b, 0x6b, 0x1a, 0xb1,
	0xe5, 0x7b, 0x8c, 0xf0, 0x60, 0xe7, 0xd8, 0xf1, 0xf8, 0x82, 0x4d, 0xfb, 0x69, 0x38, 0xc9, 0xde,
	0x02, 0xad, 0xe5, 0x6c, 0x89, 0x9e, 0x46, 0xff, 0x6f, 0x02, 0xf7, 0x6c, 0x57, 0x4d, 0x27, 0xc1,
	0x1b, 0x92, 0x3c, 0x83, 0x87, 0xbb, 0xdc, 0xdd, 0x1d, 0x77, 0x7e, 0xfa, 0x17, 0xc9, 0xfa, 0x49,
	0xf0, 0x90, 0x42, 0xa0, 0xc5, 0xfb, 0xfc, 0x74, 0x14, 0xdd, 0x73, 0xf2, 0xac, 0x18, 0x8e, 0x3e,
	0x44, 0xe4, 0x73, 0xd7, 0x3f, 0x2d, 0xaf, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xfb, 0xa2,
	0xd8, 0x6e, 0x04, 0x00, 0x00,
}
